// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file calculator.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file calculator.proto.
 */
export const file_calculator: GenFile = /*@__PURE__*/
  fileDesc("ChBjYWxjdWxhdG9yLnByb3RvIigKEkNhbGN1bGF0aW9uUmVxdWVzdBISCgpleHByZXNzaW9uGAEgASgJIiUKE0NhbGN1bGF0aW9uUmVzcG9uc2USDgoGcmVzdWx0GAEgASgJMk0KEUNhbGN1bGF0b3JTZXJ2aWNlEjgKCUNhbGN1bGF0ZRITLkNhbGN1bGF0aW9uUmVxdWVzdBoULkNhbGN1bGF0aW9uUmVzcG9uc2UiAGIGcHJvdG8z");

/**
 * 请求消息
 *
 * @generated from message CalculationRequest
 */
export type CalculationRequest = Message<"CalculationRequest"> & {
  /**
   * 表达式，例如 "1+1" 或 "1+1+1"
   *
   * @generated from field: string expression = 1;
   */
  expression: string;
};

/**
 * Describes the message CalculationRequest.
 * Use `create(CalculationRequestSchema)` to create a new message.
 */
export const CalculationRequestSchema: GenMessage<CalculationRequest> = /*@__PURE__*/
  messageDesc(file_calculator, 0);

/**
 * 响应消息
 *
 * @generated from message CalculationResponse
 */
export type CalculationResponse = Message<"CalculationResponse"> & {
  /**
   * 计算结果
   *
   * @generated from field: string result = 1;
   */
  result: string;
};

/**
 * Describes the message CalculationResponse.
 * Use `create(CalculationResponseSchema)` to create a new message.
 */
export const CalculationResponseSchema: GenMessage<CalculationResponse> = /*@__PURE__*/
  messageDesc(file_calculator, 1);

/**
 * 计算服务
 *
 * @generated from service CalculatorService
 */
export const CalculatorService: GenService<{
  /**
   * @generated from rpc CalculatorService.Calculate
   */
  calculate: {
    methodKind: "unary";
    input: typeof CalculationRequestSchema;
    output: typeof CalculationResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_calculator, 0);

